client/NavSearch: Simplify search form reset
The latest `eslint-plugin-react-hooks` update included in the next commit improved `set-state-in-effect` lint:
https://github.com/facebook/react/releases/tag/eslint-plugin-react-hooks%407.1.0

As a result `eslint` would start to fail:

    Error: Calling setState synchronously within an effect can trigger cascading renders

    Effects are intended to synchronize state between React and external systems such as manually updating the DOM, state management libraries, or other platform APIs. In general, the body of an effect should do one or both of the following:
     * Update external systems with the latest state from React.
     * Subscribe for updates from some external system, calling setState in a callback function when external state changes.

    Calling setState synchronously within an effect body causes cascading renders that can hurt performance, and is not recommended. (https://react.dev/learn/you-might-not-need-an-effect).

We can just use `key` property to automatically update the form on query string change:

- https://react.dev/learn/you-might-not-need-an-effect#resetting-all-state-when-a-prop-changes
- https://react.dev/learn/preserving-and-resetting-state#resetting-a-form-with-a-key